const myData = {
  0: [
    {
      id: 1,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 2,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 3,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 4,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 5,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 6,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }

  ],
  1: [
    {
      id: 7,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 8,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 9,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 10,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 11,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 12,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  2: [
    {
      id: 13,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 14,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 15,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 16,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 17,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 18,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  3: [
    {
      id: 19,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 20,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 21,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 22,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 23,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 24,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  4: [
    {
      id: 25,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 26,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 27,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 28,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 29,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 30,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  5: [
    {
      id: 31,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 32,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 33,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 34,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 35,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 36,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  6: [
    {
      id: 37,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 38,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 39,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 40,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 41,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 42,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
    
  ]
}
export default myData;
