const myData = {
  0: [
    {
      id: 1,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 2,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 3,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 4,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 5,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 6,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }

  ],
  1: [
    {
      id: 7,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "лекция",
      name_pair: "Структуры данных и алгоритмы",
      auditorium: "12 корпус ауд.310",
      teacher: "Кудрина Е. В.",
      type_week: "числ/знам",
    },
    {
      id: 8,
      start_time: "12:05",
      end_time: "13:40",
      type_pair: "практика",
      name_pair: "Элективные дисциплины по физической культуре и спорту",
      auditorium: "12 корпус ауд.225В",
      teacher: "Дунаев П. Д.",
      type_week: "числ/знам",
    },
    {
      id: 9,
      start_time: "13:50",
      end_time: "15:25",
      type_pair: "практика",
      name_pair: "Элективные дисциплины по физической культуре и спорту",
      auditorium: "12 корпус ауд.225В",
      teacher: "Миронов С. В.",
      type_week: "числ/знам",
    },
    {
      id: 10,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 11,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 12,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  2: [
    {
      id: 13,
      start_time: "08:21",
      end_time: "09:50",
      type_pair: "лекция",
      name_pair: "Структуры данных и алгоритмы",
      auditorium: "12 корпус ауд.230",
      teacher: "Грецова А. П.",
      type_week: "числ/знам",
    },
    {
      id: 14,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "практика",
      name_pair: "Возрастная анатомия, физиология и гигиена",
      auditorium: "12 корпус ауд.225В",
      teacher: "Лыкова Е. Ю.",
      type_week: "числ/знам",
    },
    {
      id: 15,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 16,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 17,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 18,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  3: [
    {
      id: 19,
      start_time: "08:22",
      end_time: "09:50",
      type_pair: "лекция",
      name_pair: "Структуры данных и алгоритмы",
      auditorium: "12 корпус ауд.230",
      teacher: "Грецова А. П.",
      type_week: "числ/знам",
    },
    {
      id: 20,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "практика",
      name_pair: "Возрастная анатомия, физиология и гигиена",
      auditorium: "12 корпус ауд.225В",
      teacher: "Лыкова Е. Ю.",
      type_week: "числ/знам",
    },
    {
      id: 21,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 22,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 23,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 24,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  4: [
    {
      id: 25,
      start_time: "08:23",
      end_time: "09:50",
      type_pair: "лекция",
      name_pair: "Структуры данных и алгоритмы",
      auditorium: "12 корпус ауд.230",
      teacher: "Грецова А. П.",
      type_week: "числ/знам",
    },
    {
      id: 26,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "практика",
      name_pair: "Возрастная анатомия, физиология и гигиена",
      auditorium: "12 корпус ауд.225В",
      teacher: "Лыкова Е. Ю.",
      type_week: "числ/знам",
    },
    {
      id: 27,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 28,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 29,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 30,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  5: [
    {
      id: 31,
      start_time: "08:24",
      end_time: "9:50",
      type_pair: "лекция",
      name_pair: "Структуры данных и алгоритмы",
      auditorium: "12 корпус ауд.230",
      teacher: "Грецова А. П.",
      type_week: "числ/знам",
    },
    {
      id: 32,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "практика",
      name_pair: "Возрастная анатомия, физиология и гигиена",
      auditorium: "12 корпус ауд.225В",
      teacher: "Лыкова Е. Ю.",
      type_week: "числ/знам",
    },
    {
      id: 33,
      start_time: "20:00",
      end_time: "21:30",
      type_pair: "лекция",
      name_pair: "Похуизм и эгоизм",
      auditorium: "миллеровская 15 к. 293",
      teacher: "Зельцер С. Н.",
      type_week: "числ/знам",
    },
    {
      id: 34,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 35,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 36,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
  ],
  6: [
    {
      id: 37,
      start_time: "08:20",
      end_time: "09:50",
      type_pair: "практика",
      name_pair: "Иностранный язык",
      auditorium: "12 корпус ауд.302",
      teacher: "Уколова М. В.",
      type_week: "числ/знам",
    },
    {
      id: 38,
      start_time: "10:00",
      end_time: "11:35",
      type_pair: "практика",
      name_pair: "Структуры и алгоритмы компьютерной обработки данныха",
      auditorium: "12 корпус ауд.416а",
      teacher: "Кудрина Е. В.",
      type_week: "числ/знам",
    },
    {
      id: 39,
      start_time: "12:05",
      end_time: "13:40",
      type_pair: "практика",
      name_pair: "Разработка ПО",
      auditorium: "12 корпус ауд.302",
      teacher: "Чернышова Г. Ю.",
      type_week: "числ/знам",
    },
    {
      id: 40,
      start_time: "13:50",
      end_time: "15:25",
      type_pair: "лекция",
      name_pair: "Проектирование информационных систем",
      auditorium: "12 корпус ауд.333",
      teacher: "Кабанова Л. В.",
      type_week: "числ/знам",
    },
    {
      id: 41,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    },
    {
      id: 42,
      start_time: "",
      end_time: "",
      type_pair: "лекция",
      name_pair: "",
      auditorium: "",
      teacher: "",
      type_week: "числ/знам",
    }
    
  ]
}
export default myData;
